local M = {}

local function hl(name, spec)
  vim.api.nvim_set_hl(0, name, spec)
end

local function link(name, target)
  vim.api.nvim_set_hl(0, name, { link = target })
end

function M.apply()
  local p = require("grok.palette").current()

  -- Normal stays transparent so Ghostty's GrokDay/GrokNight is the paper.
  hl("Normal", { fg = p.fg, bg = "NONE" })
  hl("NormalNC", { fg = p.fg, bg = "NONE" })
  hl("NormalFloat", { fg = p.fg, bg = p.bg_panel })
  hl("FloatBorder", { fg = p.border, bg = p.bg_panel })
  hl("FloatTitle", { fg = p.accent, bg = p.bg_panel, bold = true })
  hl("WinSeparator", { fg = p.border, bg = "NONE" })
  hl("SignColumn", { fg = p.muted, bg = "NONE" })
  hl("FoldColumn", { fg = p.faint, bg = "NONE" })
  hl("Folded", { fg = p.muted, bg = p.bg_panel })
  hl("ColorColumn", { bg = p.bg_hl })
  hl("CursorLine", { bg = p.bg_hl })
  hl("CursorLineNr", { fg = p.fg, bold = true })
  hl("CursorColumn", { bg = p.bg_hl })
  hl("LineNr", { fg = p.muted, bg = "NONE" })
  hl("LineNrAbove", { fg = p.faint })
  hl("LineNrBelow", { fg = p.faint })
  hl("EndOfBuffer", { fg = p.bg_hl, bg = "NONE" })
  hl("NonText", { fg = p.border })
  hl("Whitespace", { fg = p.border })
  hl("SpecialKey", { fg = p.faint })
  hl("Visual", { bg = p.bg_visual })
  hl("VisualNOS", { bg = p.bg_visual })
  hl("Search", { fg = p.bg, bg = p.accent })
  hl("IncSearch", { fg = p.bg, bg = p.orange })
  hl("CurSearch", { fg = p.bg, bg = p.orange })
  hl("Substitute", { fg = p.bg, bg = p.red })
  hl("MatchParen", { fg = p.accent, bold = true })
  hl("Directory", { fg = p.blue })
  hl("Title", { fg = p.accent, bold = true })
  hl("Question", { fg = p.blue })
  hl("MoreMsg", { fg = p.green })
  hl("ModeMsg", { fg = p.fg, bold = true })
  hl("ErrorMsg", { fg = p.red, bold = true })
  hl("WarningMsg", { fg = p.yellow, bold = true })
  hl("WildMenu", { fg = p.bg, bg = p.accent })
  hl("Pmenu", { fg = p.fg, bg = p.bg_panel })
  hl("PmenuSel", { fg = p.fg, bg = p.bg_visual, bold = true })
  hl("PmenuKind", { fg = p.accent, bg = p.bg_panel })
  hl("PmenuKindSel", { fg = p.accent, bg = p.bg_visual })
  hl("PmenuSbar", { bg = p.bg_hl })
  hl("PmenuThumb", { bg = p.muted })
  hl("PmenuExtra", { fg = p.muted, bg = p.bg_panel })
  hl("StatusLine", { fg = p.fg, bg = p.bg_hl })
  hl("StatusLineNC", { fg = p.muted, bg = p.bg_panel })
  hl("TabLine", { fg = p.muted, bg = p.bg_hl })
  hl("TabLineSel", { fg = p.fg, bg = "NONE", bold = true })
  hl("TabLineFill", { bg = p.bg_hl })
  hl("WinBar", { fg = p.fg, bg = "NONE" })
  hl("WinBarNC", { fg = p.muted, bg = "NONE" })
  hl("QuickFixLine", { bg = p.bg_hl })
  hl("SpellBad", { sp = p.red, undercurl = true })
  hl("SpellCap", { sp = p.yellow, undercurl = true })
  hl("SpellLocal", { sp = p.cyan, undercurl = true })
  hl("SpellRare", { sp = p.accent, undercurl = true })
  hl("Conceal", { fg = p.faint })
  hl("Cursor", { fg = p.bg, bg = p.accent })
  hl("lCursor", { fg = p.bg, bg = p.accent })
  hl("TermCursor", { fg = p.bg, bg = p.accent })

  hl("Comment", { fg = p.muted, italic = true })
  hl("Constant", { fg = p.orange })
  hl("String", { fg = p.green })
  hl("Character", { fg = p.green })
  hl("Number", { fg = p.orange })
  hl("Boolean", { fg = p.orange })
  hl("Float", { fg = p.orange })
  hl("Identifier", { fg = p.fg })
  hl("Function", { fg = p.blue })
  hl("Statement", { fg = p.accent })
  hl("Conditional", { fg = p.accent })
  hl("Repeat", { fg = p.accent })
  hl("Label", { fg = p.accent })
  hl("Operator", { fg = p.fg_dim })
  hl("Keyword", { fg = p.accent })
  hl("Exception", { fg = p.red })
  hl("PreProc", { fg = p.cyan })
  hl("Include", { fg = p.accent })
  hl("Define", { fg = p.accent })
  hl("Macro", { fg = p.accent2 })
  hl("Type", { fg = p.cyan })
  hl("StorageClass", { fg = p.cyan })
  hl("Structure", { fg = p.cyan })
  hl("Typedef", { fg = p.cyan })
  hl("Special", { fg = p.gold })
  hl("SpecialChar", { fg = p.gold })
  hl("Tag", { fg = p.accent })
  hl("Delimiter", { fg = p.fg_dim })
  hl("SpecialComment", { fg = p.muted, italic = true })
  hl("Debug", { fg = p.red })
  hl("Underlined", { underline = true })
  hl("Ignore", { fg = p.faint })
  hl("Error", { fg = p.red })
  hl("Todo", { fg = p.gold, bold = true })
  hl("Added", { fg = p.green })
  hl("Changed", { fg = p.yellow })
  hl("Removed", { fg = p.red })

  hl("DiagnosticError", { fg = p.red })
  hl("DiagnosticWarn", { fg = p.yellow })
  hl("DiagnosticInfo", { fg = p.blue })
  hl("DiagnosticHint", { fg = p.teal })
  hl("DiagnosticOk", { fg = p.green })
  hl("DiagnosticUnderlineError", { sp = p.red, undercurl = true })
  hl("DiagnosticUnderlineWarn", { sp = p.yellow, undercurl = true })
  hl("DiagnosticUnderlineInfo", { sp = p.blue, undercurl = true })
  hl("DiagnosticUnderlineHint", { sp = p.teal, undercurl = true })
  hl("DiagnosticVirtualTextError", { fg = p.red, bg = p.diff_del_bg })
  hl("DiagnosticVirtualTextWarn", { fg = p.yellow })
  hl("DiagnosticVirtualTextInfo", { fg = p.blue })
  hl("DiagnosticVirtualTextHint", { fg = p.teal })
  hl("LspReferenceText", { bg = p.bg_hl })
  hl("LspReferenceRead", { bg = p.bg_hl })
  hl("LspReferenceWrite", { bg = p.bg_hl, underline = true })
  hl("LspInlayHint", { fg = p.faint, italic = true })
  hl("LspSignatureActiveParameter", { fg = p.accent, bold = true })

  hl("DiffAdd", { bg = p.diff_add_bg })
  hl("DiffChange", { bg = p.bg_hl })
  hl("DiffDelete", { fg = p.red, bg = p.diff_del_bg })
  hl("DiffText", { fg = p.fg, bg = p.bg_visual })
  hl("GitSignsAdd", { fg = p.green })
  hl("GitSignsChange", { fg = p.yellow })
  hl("GitSignsDelete", { fg = p.red })

  link("@variable", "Identifier")
  link("@variable.builtin", "Type")
  link("@variable.parameter", "Identifier")
  link("@variable.member", "Identifier")
  link("@constant", "Constant")
  link("@constant.builtin", "Constant")
  link("@module", "Type")
  link("@string", "String")
  link("@string.escape", "SpecialChar")
  link("@character", "Character")
  link("@number", "Number")
  link("@boolean", "Boolean")
  link("@function", "Function")
  link("@function.builtin", "Special")
  link("@function.method", "Function")
  link("@constructor", "Type")
  link("@keyword", "Keyword")
  link("@keyword.function", "Keyword")
  link("@keyword.return", "Keyword")
  link("@keyword.import", "Include")
  link("@keyword.operator", "Operator")
  link("@operator", "Operator")
  link("@punctuation", "Delimiter")
  link("@punctuation.bracket", "Delimiter")
  link("@punctuation.delimiter", "Delimiter")
  link("@type", "Type")
  link("@type.builtin", "Type")
  link("@property", "Identifier")
  link("@attribute", "PreProc")
  link("@comment", "Comment")
  link("@comment.todo", "Todo")
  link("@comment.error", "Error")
  link("@comment.warning", "WarningMsg")
  link("@tag", "Tag")
  link("@tag.attribute", "Identifier")
  link("@tag.delimiter", "Delimiter")
  link("@markup.heading", "Title")
  link("@markup.strong", "Bold")
  link("@markup.italic", "Italic")
  link("@markup.link", "Underlined")
  link("@markup.raw", "String")
  link("@markup.list", "Keyword")
  hl("@markup.link.url", { fg = p.blue, underline = true })
  hl("@markup.raw.block", { fg = p.fg, bg = p.bg_panel })

  hl("SnacksNormal", { fg = p.fg, bg = p.bg_panel })
  hl("SnacksNormalNC", { fg = p.fg, bg = p.bg_panel })
  hl("SnacksWinBar", { fg = p.accent, bg = p.bg_panel, bold = true })
  hl("SnacksBackdrop", { bg = p.border })
  hl("SnacksPicker", { fg = p.fg, bg = p.bg_panel })
  hl("SnacksPickerBorder", { fg = p.border, bg = p.bg_panel })
  hl("SnacksPickerTitle", { fg = p.accent, bg = p.bg_panel, bold = true })
  hl("SnacksPickerInput", { fg = p.fg, bg = p.bg_panel })
  hl("SnacksPickerPrompt", { fg = p.accent, bg = p.bg_panel })
  hl("SnacksPickerDir", { fg = p.muted })
  hl("SnacksPickerFile", { fg = p.fg })
  hl("SnacksPickerMatch", { fg = p.red, bold = true })
  hl("SnacksPickerSelected", { fg = p.blue })
  hl("SnacksPickerCursorLine", { bg = p.bg_visual })
  hl("SnacksPickerPathHidden", { fg = p.muted })
  hl("SnacksPickerPathIgnored", { fg = p.muted })
  hl("SnacksPickerGitStatusUntracked", { fg = p.faint })
  hl("SnacksPickerGitStatusModified", { fg = p.orange })
  hl("SnacksPickerGitStatusAdded", { fg = p.green })
  hl("SnacksPickerGitStatusDeleted", { fg = p.red })
  hl("SnacksIndent", { fg = p.border })
  hl("SnacksIndentScope", { fg = p.faint })
  hl("SnacksNotifierInfo", { fg = p.blue })
  hl("SnacksNotifierWarn", { fg = p.yellow })
  hl("SnacksNotifierError", { fg = p.red })

  hl("BufferLineFill", { bg = p.bg_hl })
  hl("BufferLineBackground", { fg = p.muted, bg = p.bg_hl })
  hl("BufferLineBufferSelected", { fg = p.fg, bg = "NONE", bold = true, italic = false })
  hl("BufferLineBufferVisible", { fg = p.fg_dim, bg = p.bg_hl })
  hl("BufferLineSeparator", { fg = p.border, bg = p.bg_hl })
  hl("BufferLineSeparatorSelected", { fg = p.border, bg = "NONE" })
  hl("BufferLineSeparatorVisible", { fg = p.border, bg = p.bg_hl })
  hl("BufferLineIndicatorSelected", { fg = p.accent, bg = "NONE" })
  hl("BufferLineModified", { fg = p.orange, bg = p.bg_hl })
  hl("BufferLineModifiedSelected", { fg = p.orange, bg = "NONE" })
  hl("BufferLineCloseButton", { fg = p.faint, bg = p.bg_hl })
  hl("BufferLineCloseButtonSelected", { fg = p.muted, bg = "NONE" })

  link("TelescopeNormal", "NormalFloat")
  link("TelescopeBorder", "FloatBorder")
  link("TelescopeTitle", "FloatTitle")
  link("TelescopeSelection", "PmenuSel")
  link("TelescopeMatching", "SnacksPickerMatch")
  link("WhichKey", "Function")
  link("WhichKeyGroup", "Keyword")
  link("WhichKeyDesc", "Normal")
  link("WhichKeySeparator", "Comment")
  link("FlashLabel", "IncSearch")
  link("FlashMatch", "Search")
  link("MiniStatuslineModeNormal", "Search")
  link("BlinkCmpMenu", "Pmenu")
  link("BlinkCmpMenuSelection", "PmenuSel")
  link("BlinkCmpLabelMatch", "SnacksPickerMatch")
  link("CmpItemAbbrMatch", "SnacksPickerMatch")
  link("LazyNormal", "NormalFloat")
  link("MasonNormal", "NormalFloat")
  link("RenderMarkdownCode", "@markup.raw.block")

  hl("Bold", { bold = true })
  hl("Italic", { italic = true })

  for i, color in ipairs(p.term) do
    vim.g["terminal_color_" .. (i - 1)] = color
  end
end

return M
